### ISSUE TITLE
ERROR - The RealDebrid rclone mount is not accessible

### ISSUE THREAD

**Issue by networkneil** [I-am-PUID-0/pdrcrd#24]
**Describe the bug**

Followed the process described under [https://github.com/I-am-PUID-0/pdrcrd/wiki/Setup-Guides#windows-setup-guide-dockerwsl](url)

**To Reproduce**

Following the guide described in - [https://github.com/I-am-PUID-0/pdrcrd/wiki/Setup-Guides#windows-setup-guide-dockerwsl](url)

**Expected behavior**

RealDebrid rclone mount should be accessible.

**Screenshots**
![image](https://github.com/I-am-PUID-0/pdrcrd/assets/64820853/1f422ef5-da1d-4dd8-bdd7-ad478192f3a1)

**Please complete the following information:**
 - OS: Windows
 - Version: WIN 11
 - Supporting Applications: WSL2

**Additional context**
Portainer screenshot
![image](https://github.com/I-am-PUID-0/pdrcrd/assets/64820853/08d31621-fb9c-4a3a-996b-59c06be6252c)

**Comment by y0ungee** [comment]
Did you figure this out? i am having the same issue

**Comment by townsmcp** [comment]
I am having the same issue also :(

**Comment by I-am-PUID-0** [comment]
Did you restart the WSL2 Ubuntu instance or Windows at any point after setup? If so, you may need to enter `sudo mount --make-rshared /` in Ubuntu again, as the command does not persist reboot. 
Additionally, to view any possible issues with the rclone_RD process, try disabling plex_debrid and enable DEBUG logging for rclone.

**Comment by lolo45** [comment]
I am having the same issue also :(
Jan 18, 2024 16:44:55 - ERROR - The RealDebrid rclone mount is not accessible
under Synology DSM 7.2 Installed from Container Manager (ex docker)
I'm goig to try your "sudo mount --make-rshared " but I'm not a command line specialist...

**Comment by I-am-PUID-0** [comment]
> I am having the same issue also :( Jan 18, 2024 16:44:55 - ERROR - The RealDebrid rclone mount is not accessible under Synology DSM 7.2 Installed from Container Manager (ex docker) I'm goig to try your "sudo mount --make-rshared " but I'm not a command line specialist...

https://github.com/I-am-PUID-0/pdrcrd/wiki/FAQ#error-response-from-daemon-path-yourhostpathpdrcrdmnt-is-mounted-on--but-it-is-not-a-shared-mount

**Comment by lolo45** [comment]
My tree under docker directory is pdrcrd with 3 subdirectories : config, log, mnt (my mount for rclone)
ooops... not available, what am I doing wrong ?  
NAS : /volume1/docker/pdrcrd$ sudo mount --make-rshared mnt
mount : /volume1/docker/pdrcrd/mnt : not mount point or bad option.

**Comment by I-am-PUID-0** [comment]
> My tree under docker directory is pdrcrd with 3 subdirectories : config, log, mnt (my mount for rclone) ooops... not available, what am I doing wrong ? NAS : /volume1/docker/pdrcrd$ sudo mount --make-rshared mnt mount : /volume1/docker/pdrcrd/mnt : not mount point or bad option.

`sudo mount --make-rshared /volume1/`

**Comment by lolo45** [comment]
thxs, but very affraid of doing this on entire /volume1/
sudo mount --make-rshared /volume1/
if so, will it be persistent ? and am i to fearful for the rshared entire volume ?

**Comment by I-am-PUID-0** [comment]
> thxs, but very affraid of doing this on entire /volume1/ sudo mount --make-rshared /volume1/ if so, will it be persistent ? and am i to fearful for the rshared entire volume ?

The command does not persist reboots.

**Comment by lolo45** [comment]
Unfortunately, even with "sudo mount --make-rshared /volume1/" it doesn't work. An idea ? and about fuse, do you have any advice ?  how do I know if the fuse device is active?

**Comment by I-am-PUID-0** [comment]
> DSM 7.2

On Discord, there has been mention of issues with fusermount after updating to DSM 7.2 with no metions of a resolution. 

A couple of options to try:

1. Add `/bin/fusermount:/usr/bin/fusermount:rwm` to the pdrcrd service under devices. 

2. Try pd_zurg to see if you get different results: https://github.com/I-am-PUID-0/pd_zurg

**Comment by I-am-PUID-0** [comment]
Resolved with Version [1.4.2]
