### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by paulerrr** [I-am-PUID-0/pdrcrd#3]
I attempted to install via the Docker/WSL setup guide. When I ran the last line, ./pdrcrd_ubuntu_install.sh, I received this error response:

./pdrcrd_ubuntu_install.sh: line 8: syntax error near unexpected token `newline'

./pdrcrd_ubuntu_install.sh: line 8: ` <!DOCTYPE html> '

Running Ubuntu 22.04 on Windows 11 w/ WSL 2

**Comment by I-am-PUID-0** [comment]
Had the wrong link for the curl command. try this: ```curl -o pdrcrd_ubuntu_install.sh https://raw.githubusercontent.com/I-am-PUID-0/pdrcrd/master/Ubuntu/pdrcrd_ubuntu_install.sh  && chmod +x pdrcrd_ubuntu_install.sh```
