### ISSUE TITLE
AllDebrid support in rclone_RD

### ISSUE THREAD

**Issue by dbz2k** [I-am-PUID-0/pdrcrd#7]
Hello, I was was wondering if you could support AllDebrid in  rclone_RD container?

**Comment by I-am-PUID-0** [comment]
Added to the roadmap.

**Comment by I-am-PUID-0** [comment]
@dbz2k, AllDebrid support has been added in Version [1.4.0], available on the [refactoring branch](https://github.com/I-am-PUID-0/pdrcrd/tree/refactoring) for testing. It can be pulled from the docker hub with `iampuid0/refactored-pdrcrd:latest`

**Comment by I-am-PUID-0** [comment]
Support added in Version [1.4.1]
